{% set name = "debuglater" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/debuglater-{{ version }}.tar.gz
  sha256: f3a388acff38006774ad775f191edfa34268b6d5d92dcfa0a9b2cc1f771dfb1e

build:
  entry_points:
    - debuglater=debuglater.cli:main
    - dltr=debuglater.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - python >={{ python_min }}

test:
  imports:
    - debuglater
  commands:
    - pip check
    - debuglater --help
    - dltr --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ploomber/debuglater
  summary: Post-mortem debugging for Python programs
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - edublancas
